In [2]:
from datasets import load_dataset

dataset = load_dataset("jquigl/imdb-genres")

c:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
train_data = dataset["train"]
print(train_data[0])

{'movie title - year': 'Flaming Ears - 1992', 'genre': 'Fantasy', 'expanded-genres': 'Fantasy, Sci-Fi', 'rating': 6.0, 'description': 'Flaming Ears is a pop sci-fi lesbian fantasy feature set in the year 2700 in the fictive burned-out city of Asche. It follows the tangled lives of three women - Volley, Nun and Spy.'}

In [4]:
import pandas as pd

df = train_data.to_pandas()
df.head()

,movie title - year,genre,expanded-genres,rating,description
0,Flaming Ears - 1992,Fantasy,"Fantasy, Sci-Fi",6.0,Flaming Ears is a pop sci-fi lesbian fantasy f...
1,Jeg elsker dig - 1957,Romance,"Comedy, Drama, Romance",5.8,Six people - three couples - meet at random at...
2,Povjerenje - 2021,Thriller,Thriller,NaN,"In a small unnamed town, in year 2025, Krsto w..."
3,Gulliver Returns - 2021,Fantasy,"Animation, Adventure, Family",4.4,The legendary Gulliver returns to the Kingdom ...
4,Prithvi Vallabh - 1924,Biography,"Biography, Drama, Romance",NaN,"Seminal silent historical film, the story feat..."

In [5]:
int(df["rating"].isnull().sum())

69721

In [6]:
df.shape

(238256, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238256 entries, 0 to 238255
Data columns (total 5 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   movie title - year  238256 non-null  object
 1   genre               238256 non-null  object
 2   expanded-genres     238256 non-null  object
 3   rating              168535 non-null  float64
 4   description         238256 non-null  object
dtypes: float64(1), object(4)
memory usage: 9.1+ MB

In [8]:
(df['rating']=='NaN').sum()

np.int64(0)

In [9]:
df.isnull().sum()

movie title - year        0
genre                     0
expanded-genres           0
rating                69721
description               0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(18)

In [11]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 238238 entries, 0 to 238255
Data columns (total 5 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   movie title - year  238238 non-null  object
 1   genre               238238 non-null  object
 2   expanded-genres     238238 non-null  object
 3   rating              168533 non-null  float64
 4   description         238238 non-null  object
dtypes: float64(1), object(4)
memory usage: 10.9+ MB

In [13]:
df.isnull().sum()

movie title - year        0
genre                     0
expanded-genres           0
rating                69705
description               0
dtype: int64

In [23]:
df.head(3)

,movie title - year,genre,expanded-genres,rating,description,tags,title
0,Flaming Ears - 1992,Fantasy,"Fantasy, Sci-Fi",6.0,Flaming Ears is a pop sci-fi lesbian fantasy f...,Flaming Ears is a pop sci-fi lesbian fantasy f...,Flaming Ears
1,Jeg elsker dig - 1957,Romance,"Comedy, Drama, Romance",5.8,Six people - three couples - meet at random at...,Six people - three couples - meet at random at...,Jeg elsker dig
2,Povjerenje - 2021,Thriller,Thriller,NaN,"In a small unnamed town, in year 2025, Krsto w...","In a small unnamed town, in year 2025, Krsto w...",Povjerenje

In [26]:
df['title'] = df['movie title - year'].str.split(' -').str[0]
df['year'] = df['movie title - year'].str.split(' -').str[1]

In [28]:
df['tags'] = df['description'] + df['genre'] + df['expanded-genres']
df.head(1)

,movie title - year,genre,expanded-genres,rating,description,tags,title,year
0,Flaming Ears - 1992,Fantasy,"Fantasy, Sci-Fi",6.0,Flaming Ears is a pop sci-fi lesbian fantasy f...,Flaming Ears is a pop sci-fi lesbian fantasy f...,Flaming Ears,1992

In [31]:
movies = df[['title','tags', 'rating', 'year' ]]
movies.head(2)

,title,tags,rating,year
0,Flaming Ears,Flaming Ears is a pop sci-fi lesbian fantasy f...,6.0,1992
1,Jeg elsker dig,Six people - three couples - meet at random at...,5.8,1957

In [32]:
movies['tags'][0]

'Flaming Ears is a pop sci-fi lesbian fantasy feature set in the year 2700 in the fictive burned-out city of Asche. It follows the tangled lives of three women - Volley, Nun and Spy.FantasyFantasy, Sci-Fi'

Data Preprocessing